<template>
  <main class="tournament-page">
    <section class="tournament-hero">
      <span class="live"><i /> {{ tournament.active ? 'Torneio ativo' : 'Campanha em destaque' }}</span>
      <h1>{{ tournament.title }}</h1><p>{{ tournament.description }}</p>
      <div class="deadline"><Icon name="ph:calendar-check-bold" /><span>Período<strong>{{ formatDate(tournament.startsAt) }} — {{ formatDate(tournament.endsAt) }}</strong></span></div>
    </section>
    <section class="podium" aria-label="Pódio do torneio">
      <article v-for="entry in podium" :key="entry.position" :class="`place-${entry.position}`"><Icon name="ph:medal-fill" /><strong>{{ entry.name }}</strong><span>{{ entry.score.toLocaleString('pt-BR') }} pts</span><b>{{ entry.position }}º</b></article>
    </section>
    <div class="tournament-grid">
      <section class="glass-panel"><h2><Icon name="ph:trophy-bold" /> Premiações</h2><ol><li v-for="prize in tournament.prizes" :key="prize">{{ prize }}</li></ol></section>
      <section class="glass-panel"><h2><Icon name="ph:list-checks-bold" /> Regras</h2><ul><li v-for="rule in tournament.rules" :key="rule">{{ rule }}</li></ul></section>
    </div>
    <section class="ranking-panel"><header><div><span>Classificação</span><h2>Ranking geral</h2></div><small>Atualizado automaticamente</small></header><div class="ranking-row" v-for="entry in tournament.ranking" :key="entry.position"><b>#{{ entry.position }}</b><span>{{ entry.name }}</span><strong>{{ entry.score.toLocaleString('pt-BR') }} pts</strong></div></section>
  </main>
</template>
<script setup lang="ts">
definePageMeta({ layout: 'default' })
const mock = { title:'Desafio dos Membros',description:'Participe, acumule pontos e concorra a benefícios exclusivos.',startsAt:new Date().toISOString(),endsAt:new Date(Date.now()+7*86400000).toISOString(),active:true,prizes:['1º lugar — Prêmio VIP','2º lugar — Bônus especial','3º lugar — Kit exclusivo'],rules:['Válido para membros ativos.','A classificação considera os pontos do período.','Empates são definidos pela participação mais antiga.'],ranking:[{position:1,name:'Ana M.',score:9850},{position:2,name:'Carlos R.',score:8720},{position:3,name:'Bia S.',score:7990},{position:4,name:'Rafael P.',score:6840},{position:5,name:'Luiza C.',score:6210}] }
const { data } = await useFetch<any>('/api/tournaments')
const tournament = computed(() => data.value?.tournament || mock)
const podium = computed(() => [tournament.value.ranking[1],tournament.value.ranking[0],tournament.value.ranking[2]].filter(Boolean))
const formatDate=(value:string)=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value))
</script>
<style scoped>
.tournament-page{min-height:100vh;padding:clamp(20px,4vw,48px);background:radial-gradient(circle at 70% 0,color-mix(in srgb,var(--color-primary) 14%,transparent),transparent 40%),var(--bg-dark);color:var(--text-main)}.tournament-hero{max-width:1000px;margin:auto;padding:clamp(28px,6vw,64px);border:1px solid var(--card-border);border-radius:28px;background:linear-gradient(140deg,color-mix(in srgb,var(--color-primary) 12%,var(--card-bg)),var(--bg-darker));box-shadow:0 25px 70px #0005}.live{display:inline-flex;align-items:center;gap:8px;color:var(--color-secondary);font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:.12em}.live i{width:8px;height:8px;border-radius:50%;background:#4ade80;box-shadow:0 0 0 5px #4ade8022}.tournament-hero h1{max-width:700px;margin:12px 0;font-size:clamp(34px,7vw,68px);line-height:1}.tournament-hero>p{max-width:650px;color:var(--text-muted);font-size:17px;line-height:1.7}.deadline{display:flex;align-items:center;gap:12px;margin-top:25px}.deadline>svg{font-size:26px;color:var(--color-primary)}.deadline span{display:grid;color:var(--text-muted);font-size:11px}.deadline strong{color:var(--text-main);font-size:14px}.podium{display:flex;align-items:end;justify-content:center;gap:12px;max-width:760px;margin:55px auto 28px}.podium article{position:relative;display:grid;justify-items:center;gap:5px;width:31%;min-height:150px;padding:24px 10px;border:1px solid var(--card-border);border-radius:20px 20px 8px 8px;background:var(--card-bg)}.podium article>svg{font-size:35px}.podium article>b{position:absolute;bottom:-14px;display:grid;place-items:center;width:32px;height:32px;border-radius:50%;background:var(--component-bg)}.podium .place-1{min-height:190px;border-color:#d9b76e}.place-1>svg{color:#d9b76e}.place-2>svg{color:#bac3cf}.place-3>svg{color:#bc7b46}.podium article span{color:var(--text-muted);font-size:12px}.tournament-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;max-width:1000px;margin:45px auto 18px}.glass-panel,.ranking-panel{padding:26px;border:1px solid var(--card-border);border-radius:20px;background:color-mix(in srgb,var(--card-bg) 91%,transparent);box-shadow:0 14px 40px #0003}.glass-panel h2{display:flex;gap:9px;margin-bottom:16px}.glass-panel li{margin:10px 0;color:var(--text-muted);line-height:1.5}.ranking-panel{max-width:1000px;margin:auto}.ranking-panel header{display:flex;justify-content:space-between;align-items:end;margin-bottom:15px}.ranking-panel header span{color:var(--color-primary);font-size:11px;font-weight:900;text-transform:uppercase}.ranking-panel small{color:var(--text-muted)}.ranking-row{display:grid;grid-template-columns:55px 1fr auto;gap:12px;padding:15px 8px;border-top:1px solid var(--card-border)}.ranking-row>b{color:var(--color-primary)}@media(max-width:650px){.tournament-grid{grid-template-columns:1fr}.podium{gap:5px}.podium article{font-size:12px}.ranking-row{grid-template-columns:42px 1fr}.ranking-row strong{grid-column:2}}
</style>
